### ISSUE TITLE
Suggestion: composer update also with --no-dev

### ISSUE THREAD

**Issue by mariolorenz** [OXID-eSales/oxideshop-user-documentation#6]
Hi,
i follow the instructions for update an 6.0 OXID.

For the OXID composer installation, you recommend using the --no-dev option. I would also mention this option in the composer update. Otherwise, only unnecessary material (including Azure Theme, etc.) will be installed during the update.

Regards, Mario

**Comment by Juergen-Busch** [comment]
Hi Mario,

thanks for your hint. I added the --no-dev parameter to the composer update. See: https://github.com/OXID-eSales/oxideshop-user-documentation/commit/45982d90573f50a1364da26a5bdd1a7789d1dfac.
 
Regards, Jürgen
